### PR TITLE
Added Purpose

### PR DESCRIPTION
**Pull request by RupinderN**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
We should not be talking about how we're solving the problem (or the problem itself). Specifics like 'Web App', 'Bluetooth' should not be mentioned here. 

Spelling mistake for Chess Connect. Just use \progname{} in latex.

**Comment by ghost** [comment]
Should also be merged into Documents/SRS branch, not main.

**Comment by vankraa** [comment]
> Should also be merged into Documents/SRS branch, not main.

@celsj No, we want to merge from whatever branch into main. Pull requests would always be for merging into main because that's what we submit at the end of the day. Other branches are for doing whatever you like without worrying about messing up the submission. Think of other branches like rough drafts and main like final drafts.

For the latex docs it wouldn't matter what branch it comes from, but when making changes to the webapp or the embedded code we should follow the branch pattern I mentioned in discord.

**Comment by aujlaa4** [comment]
> Should also be merged into Documents/SRS branch, not main.

**Comment by vankraa** [comment]
Should be merged into Documentation/SRS, not main

**Comment by vankraa** [comment]
@RupinderN you put the purpose description under the Assumptions header. Should be moved to Document Purpose section above.

**Pull request closed without merging**
